/**
 * Jest tests for the JS wrapper in src/index.ts.
 *
 * These tests don't exercise the native PDFBox / PDFKit code — that's covered
 * by the platform-specific tests in android/src/androidTest and ios/. They
 * verify the wrapper's own logic, which still needs to hold even if the
 * ios/ and android/ folders are regenerated by `expo prebuild`:
 *   - optional password is threaded through to the native module
 *   - error codes from the native module are mapped to PdfErrorCode
 *   - extractTextWithInfo populates isEncrypted / passwordRequired correctly
 *   - argument validation
 */

// Hold a reference to the fake native module that requireNativeModule returns.
// Each test resets its mocks and behaviour via beforeEach.
const fakeNative = {
  extractText: jest.fn(),
  getPageCount: jest.fn(),
  extractTextFromPage: jest.fn(),
  isPasswordProtected: jest.fn(),
  isAvailable: jest.fn(() => true),
};

jest.mock('expo-modules-core', () => ({
  requireNativeModule: jest.fn(() => fakeNative),
}));

// Import after the mock is in place.
import {
  extractText,
  getPageCount,
  extractTextFromPage,
  isPasswordProtected,
  extractTextWithInfo,
  isAvailable,
} from '../src/index';

function codedError(code: string, message = code): Error & { code: string } {
  const err = new Error(message) as Error & { code: string };
  err.code = code;
  return err;
}

beforeEach(() => {
  jest.clearAllMocks();
  fakeNative.isAvailable.mockReturnValue(true);
});

describe('isAvailable', () => {
  it('returns true when the native module loaded', () => {
    expect(isAvailable()).toBe(true);
  });

  it('returns false when the native module throws', () => {
    fakeNative.isAvailable.mockImplementationOnce(() => {
      throw new Error('boom');
    });
    expect(isAvailable()).toBe(false);
  });
});

describe('extractText', () => {
  it('threads no password through as null (backward compat)', async () => {
    fakeNative.extractText.mockResolvedValueOnce('hello');
    const text = await extractText('/tmp/a.pdf');
    expect(text).toBe('hello');
    expect(fakeNative.extractText).toHaveBeenCalledWith('/tmp/a.pdf', null);
  });

  it('threads the supplied password through to the native module', async () => {
    fakeNative.extractText.mockResolvedValueOnce('secret');
    await extractText('/tmp/a.pdf', 'pw');
    expect(fakeNative.extractText).toHaveBeenCalledWith('/tmp/a.pdf', 'pw');
  });

  it('propagates PASSWORD_REQUIRED from the native module', async () => {
    fakeNative.extractText.mockRejectedValueOnce(codedError('PASSWORD_REQUIRED'));
    await expect(extractText('/tmp/a.pdf')).rejects.toMatchObject({
      code: 'PASSWORD_REQUIRED',
    });
  });

  it('propagates INCORRECT_PASSWORD from the native module', async () => {
    fakeNative.extractText.mockRejectedValueOnce(codedError('INCORRECT_PASSWORD'));
    await expect(extractText('/tmp/a.pdf', 'wrong')).rejects.toMatchObject({
      code: 'INCORRECT_PASSWORD',
    });
  });

  it('throws when filePath is empty', async () => {
    await expect(extractText('')).rejects.toThrow('File path is required');
    expect(fakeNative.extractText).not.toHaveBeenCalled();
  });
});

describe('getPageCount', () => {
  it('threads no password through as null', async () => {
    fakeNative.getPageCount.mockResolvedValueOnce(3);
    const count = await getPageCount('/tmp/a.pdf');
    expect(count).toBe(3);
    expect(fakeNative.getPageCount).toHaveBeenCalledWith('/tmp/a.pdf', null);
  });

  it('threads the password through', async () => {
    fakeNative.getPageCount.mockResolvedValueOnce(7);
    await getPageCount('/tmp/a.pdf', 'pw');
    expect(fakeNative.getPageCount).toHaveBeenCalledWith('/tmp/a.pdf', 'pw');
  });
});

describe('extractTextFromPage', () => {
  it('threads page number and no password', async () => {
    fakeNative.extractTextFromPage.mockResolvedValueOnce('page 2');
    await extractTextFromPage('/tmp/a.pdf', 2);
    expect(fakeNative.extractTextFromPage).toHaveBeenCalledWith('/tmp/a.pdf', 2, null);
  });

  it('threads page number and password', async () => {
    fakeNative.extractTextFromPage.mockResolvedValueOnce('page 2');
    await extractTextFromPage('/tmp/a.pdf', 2, 'pw');
    expect(fakeNative.extractTextFromPage).toHaveBeenCalledWith('/tmp/a.pdf', 2, 'pw');
  });

  it('rejects page numbers below 1 without calling the native module', async () => {
    await expect(extractTextFromPage('/tmp/a.pdf', 0)).rejects.toThrow(/Page number/);
    expect(fakeNative.extractTextFromPage).not.toHaveBeenCalled();
  });
});

describe('isPasswordProtected', () => {
  it('returns whatever the native module returns', async () => {
    fakeNative.isPasswordProtected.mockResolvedValueOnce(true);
    expect(await isPasswordProtected('/tmp/a.pdf')).toBe(true);

    fakeNative.isPasswordProtected.mockResolvedValueOnce(false);
    expect(await isPasswordProtected('/tmp/a.pdf')).toBe(false);
  });

  it('throws when filePath is empty', async () => {
    await expect(isPasswordProtected('')).rejects.toThrow('File path is required');
  });
});

describe('extractTextWithInfo', () => {
  it('clear PDF: success path returns isEncrypted=false', async () => {
    fakeNative.isPasswordProtected.mockResolvedValueOnce(false);
    fakeNative.extractText.mockResolvedValueOnce('hello world');
    fakeNative.getPageCount.mockResolvedValueOnce(1);

    const r = await extractTextWithInfo('/tmp/clear.pdf');
    expect(r).toEqual({
      text: 'hello world',
      pageCount: 1,
      success: true,
      isEncrypted: false,
    });
  });

  it('encrypted + no password: returns passwordRequired=true with PASSWORD_REQUIRED code, no throw', async () => {
    fakeNative.isPasswordProtected.mockResolvedValueOnce(true);
    fakeNative.extractText.mockRejectedValueOnce(codedError('PASSWORD_REQUIRED'));
    fakeNative.getPageCount.mockRejectedValueOnce(codedError('PASSWORD_REQUIRED'));

    const r = await extractTextWithInfo('/tmp/locked.pdf');
    expect(r.success).toBe(false);
    expect(r.isEncrypted).toBe(true);
    expect(r.passwordRequired).toBe(true);
    expect(r.errorCode).toBe('PASSWORD_REQUIRED');
    expect(r.text).toBe('');
    expect(r.pageCount).toBe(0);
  });

  it('encrypted + correct password: success with isEncrypted=true', async () => {
    fakeNative.isPasswordProtected.mockResolvedValueOnce(true);
    fakeNative.extractText.mockResolvedValueOnce('decrypted');
    fakeNative.getPageCount.mockResolvedValueOnce(2);

    const r = await extractTextWithInfo('/tmp/locked.pdf', 'pw');
    expect(r).toEqual({
      text: 'decrypted',
      pageCount: 2,
      success: true,
      isEncrypted: true,
    });
  });

  it('encrypted + wrong password: returns passwordRequired=true with INCORRECT_PASSWORD code', async () => {
    fakeNative.isPasswordProtected.mockResolvedValueOnce(true);
    fakeNative.extractText.mockRejectedValueOnce(codedError('INCORRECT_PASSWORD'));
    fakeNative.getPageCount.mockRejectedValueOnce(codedError('INCORRECT_PASSWORD'));

    const r = await extractTextWithInfo('/tmp/locked.pdf', 'wrong');
    expect(r.success).toBe(false);
    expect(r.isEncrypted).toBe(true);
    expect(r.passwordRequired).toBe(true);
    expect(r.errorCode).toBe('INCORRECT_PASSWORD');
  });

  it('unknown native error: errorCode is UNKNOWN, passwordRequired is undefined', async () => {
    fakeNative.isPasswordProtected.mockResolvedValueOnce(false);
    fakeNative.extractText.mockRejectedValueOnce(new Error('something else'));
    fakeNative.getPageCount.mockRejectedValueOnce(new Error('something else'));

    const r = await extractTextWithInfo('/tmp/x.pdf');
    expect(r.success).toBe(false);
    expect(r.errorCode).toBe('UNKNOWN');
    expect(r.passwordRequired).toBeUndefined();
    expect(r.isEncrypted).toBe(false);
  });

  it('FILE_NOT_FOUND code maps through correctly', async () => {
    fakeNative.isPasswordProtected.mockRejectedValueOnce(codedError('FILE_NOT_FOUND'));
    fakeNative.extractText.mockRejectedValueOnce(codedError('FILE_NOT_FOUND'));
    fakeNative.getPageCount.mockRejectedValueOnce(codedError('FILE_NOT_FOUND'));

    const r = await extractTextWithInfo('/missing.pdf');
    expect(r.success).toBe(false);
    expect(r.errorCode).toBe('FILE_NOT_FOUND');
    expect(r.passwordRequired).toBeUndefined();
  });

  it('isPasswordProtected probe failing is non-fatal: extraction still attempted', async () => {
    fakeNative.isPasswordProtected.mockRejectedValueOnce(new Error('probe failed'));
    fakeNative.extractText.mockResolvedValueOnce('text');
    fakeNative.getPageCount.mockResolvedValueOnce(1);

    const r = await extractTextWithInfo('/tmp/a.pdf');
    expect(r.success).toBe(true);
    expect(r.text).toBe('text');
    expect(r.isEncrypted).toBe(false);
  });
});
